include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  errors:
    sort_pub_dependencies: ignore
    unused_element: ignore
    always_use_package_imports: ignore
    inference_failure_on_instance_creation: ignore
    inference_failure_on_function_invocation: ignore
    depend_on_referenced_packages: ignore
    cascade_invocations: ignore
    avoid_field_initializers_in_const_classes: ignore
    public_member_api_docs: ignore
    use_setters_to_change_properties: ignore
    avoid_positional_boolean_parameters: ignore
    lines_longer_than_80_chars: ignore
    # unused_local_variable: ignore
    # unused_import: ignore
    # argument_type_not_assignable: ignore
    # lines_longer_than_80_chars: ignore
    # one_member_abstracts: ignore
    # only_throw_errors: ignore
    # avoid_setters_without_getters: ignore
    # inference_failure_on_untyped_parameter: ignore
    # directives_ordering: ignore

  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "packages/**"
