name: app_database
version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  financo:
    path: ../../
  app_core:
    path: ../app_core
  flutter:
    sdk: flutter
  drift: ^2.28.2
  path: ^1.8.0


dev_dependencies:
  build_runner: ^2.9.0
  drift_dev: ^2.28.3
