name: financo

packages:
  - .

command:
  bootstrap:
    hooks:
      post: melos run build_runner

scripts:
  build_runner:
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: "build_runner"

  generate_routes: 
    run: dart run financo:routes

  slang: 
    run: dart run slang

  generate_assets_folders: 
    run: dart run financo:assets

  packages_update:
    run: dart pub outdated
    
  run_release:
    run: flutter run --release

