name: financo

packages:
  - .

command:
  bootstrap:
    hooks:
      post: melos run build_runner

scripts:
  build_runner_app_database_by_path:
    run: cmd /C "cd /d C:\Users\Guilherme\Documents\Projetos\financo\packages\app_database && dart run build_runner build --delete-conflicting-outputs"


  generate_routes: 
    run: dart run financo:routes

  slang: 
    run: dart run slang

  generate_assets_folders: 
    run: dart run financo:assets

  packages_update:
    run: dart pub outdated
    
  run_release:
    run: flutter run --release

