name: financo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang_flutter: ^4.8.0

dev_dependencies:
  flutter_lints: ^6.0.0
  melos: ^6.3.3
  intl: ^0.20.2
  slang: ^4.8.1
  very_good_analysis: 9.0.0


workspace:
  - packages/app_core
  - packages/app_widgets
  - packages/app_database

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: lib/app/assets/fonts/Inter_Regular.ttf
          weight: 200
        - asset: lib/app/assets/fonts/Inter_Bold.ttf
          weight: 700


  assets:
    - lib/app/assets/excels/
    - lib/app/assets/fonts/
    - lib/app/assets/i18n/
    - lib/app/assets/images/
    - lib/app/assets/images/banks/
    - lib/app/assets/images/flags/
    - lib/app/assets/svgs/