name: financo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  app_core:
    path: packages/app_core
  app_database:
    path: packages/app_database
  app_widgets:
    path: packages/app_widgets
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang_flutter: ^4.8.0

dev_dependencies:
  flutter_lints: ^6.0.0
  intl: ^0.20.2
  melos: ^7.1.1
  slang: ^4.8.1
  very_good_analysis: ^10.0.0

dependency_overrides:
  very_good_analysis: ^10.0.0

workspace:
  - packages/app_core
  - packages/app_widgets
  - packages/app_database

melos:
  scripts:
    build_runner_app_database_by_path:
      run: cd packages/app_database && dart run build_runner build --delete-conflicting-outputs

    generate_routes:
      run: dart run financo:routes

    slang:
      run: dart run slang
    
    generate_assets_folders:
      run: dart run financo:assets
      
    packages_update:
      run: dart pub outdated

    run_release:
      run: flutter run --release

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: lib/app/assets/fonts/Inter_Regular.ttf
          weight: 200
        - asset: lib/app/assets/fonts/Inter_Bold.ttf
          weight: 700


  assets:
    - lib/app/assets/fonts/
    - lib/app/assets/i18n/
    - lib/app/assets/images/
    - lib/app/assets/images/banks/
    - lib/app/assets/images/flags/