name: financo
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  melos: ^6.3.3
  intl: ^0.20.2

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: lib/app/assets/fonts/Inter_Regular.ttf
          weight: 200
        - asset: lib/app/assets/fonts/Inter_Bold.ttf
          weight: 700


  assets:
    - lib/app/assets/fonts/
    - lib/app/assets/svgs/