// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdmUz0jEyvQq5PXtZIs8DgLa9WZk5Gao',
    appId: '1:356891758869:web:877c4a777ad7e8314dd91c',
    messagingSenderId: '356891758869',
    projectId: 'financo-app-2026',
    authDomain: 'financo-app-2026.firebaseapp.com',
    storageBucket: 'financo-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtiBk856VV_H57HpcIstc5E5yFgPoqV6M',
    appId: '1:356891758869:android:028ae37486c30b8f4dd91c',
    messagingSenderId: '356891758869',
    projectId: 'financo-app-2026',
    storageBucket: 'financo-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO6Qvv3n-WOn5Gy-kjRP_ywN8cJZZV4gk',
    appId: '1:356891758869:ios:328b46c5194e20d14dd91c',
    messagingSenderId: '356891758869',
    projectId: 'financo-app-2026',
    storageBucket: 'financo-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.financo',
  );
}
