// Justification: this catalog is a tabular data file — each entry is a
// single-line "row" (icon + keywords) so the list reads like a table and
// stays easy to scan/edit when adding new icons. Splitting every entry
// across four lines would quadruple the file size with no semantic gain.
// ignore_for_file: lines_longer_than_80_chars

import 'package:financo/features/categories/domain/category_icon_option.dart';
import 'package:flutter/material.dart';

/// Curated list of Material icons offered in the category icon picker,
/// each tagged with bilingual keywords (English + Portuguese, no
/// diacritics) so the search field works for both languages.
///
/// Order is loosely thematic (money, food, transport, ...) so the grid
/// reads naturally when the search field is empty.
const categoryIconCatalog = <CategoryIconOption>[
  // ── Money & finance ──────────────────────────────────────────────
  CategoryIconOption(icon: Icons.attach_money, keywords: 'money dinheiro cash dolar dollar salary salario'),
  CategoryIconOption(icon: Icons.account_balance_wallet, keywords: 'wallet carteira money dinheiro'),
  CategoryIconOption(icon: Icons.account_balance, keywords: 'bank banco account conta finance financa'),
  CategoryIconOption(icon: Icons.savings, keywords: 'savings poupanca piggy cofre'),
  CategoryIconOption(icon: Icons.credit_card, keywords: 'credit card cartao credito'),
  CategoryIconOption(icon: Icons.payment, keywords: 'payment pagamento card cartao'),
  CategoryIconOption(icon: Icons.paid, keywords: 'paid pago payment pagamento'),
  CategoryIconOption(icon: Icons.monetization_on, keywords: 'coin moeda money dinheiro'),
  CategoryIconOption(icon: Icons.request_quote, keywords: 'invoice fatura quote orcamento'),
  CategoryIconOption(icon: Icons.receipt, keywords: 'receipt recibo nota fiscal'),
  CategoryIconOption(icon: Icons.receipt_long, keywords: 'bill conta receipt recibo invoice fatura'),
  CategoryIconOption(icon: Icons.currency_exchange, keywords: 'exchange cambio currency moeda'),
  CategoryIconOption(icon: Icons.price_change, keywords: 'price preco change variacao'),
  CategoryIconOption(icon: Icons.local_atm, keywords: 'atm caixa bank banco withdraw saque'),
  CategoryIconOption(icon: Icons.trending_up, keywords: 'investment investimento gain ganho profit lucro'),
  CategoryIconOption(icon: Icons.trending_down, keywords: 'loss perda decrease queda'),
  CategoryIconOption(icon: Icons.show_chart, keywords: 'chart grafico market mercado stock acoes'),
  CategoryIconOption(icon: Icons.pie_chart, keywords: 'budget orcamento chart grafico'),
  CategoryIconOption(icon: Icons.account_balance_outlined, keywords: 'tax imposto government governo'),

  // ── Food & drink ─────────────────────────────────────────────────
  CategoryIconOption(icon: Icons.restaurant, keywords: 'restaurant restaurante food comida dining'),
  CategoryIconOption(icon: Icons.restaurant_menu, keywords: 'menu cardapio restaurant restaurante'),
  CategoryIconOption(icon: Icons.fastfood, keywords: 'fastfood burger hamburguer lanche'),
  CategoryIconOption(icon: Icons.lunch_dining, keywords: 'lunch almoco sandwich sanduiche'),
  CategoryIconOption(icon: Icons.dinner_dining, keywords: 'dinner jantar pasta macarrao'),
  CategoryIconOption(icon: Icons.brunch_dining, keywords: 'brunch breakfast cafe da manha'),
  CategoryIconOption(icon: Icons.breakfast_dining, keywords: 'breakfast cafe da manha croissant'),
  CategoryIconOption(icon: Icons.local_pizza, keywords: 'pizza pizzaria'),
  CategoryIconOption(icon: Icons.ramen_dining, keywords: 'ramen lamen noodle macarrao asian asiatica'),
  CategoryIconOption(icon: Icons.kebab_dining, keywords: 'kebab churrasco grill grelha'),
  CategoryIconOption(icon: Icons.bakery_dining, keywords: 'bakery padaria bread pao'),
  CategoryIconOption(icon: Icons.icecream, keywords: 'icecream sorvete dessert sobremesa'),
  CategoryIconOption(icon: Icons.cake, keywords: 'cake bolo birthday aniversario dessert'),
  CategoryIconOption(icon: Icons.local_cafe, keywords: 'coffee cafe latte espresso'),
  CategoryIconOption(icon: Icons.coffee, keywords: 'coffee cafe drink bebida'),
  CategoryIconOption(icon: Icons.local_bar, keywords: 'bar drink bebida alcohol cocktail'),
  CategoryIconOption(icon: Icons.wine_bar, keywords: 'wine vinho bar drink bebida'),
  CategoryIconOption(icon: Icons.sports_bar, keywords: 'beer cerveja bar pub'),
  CategoryIconOption(icon: Icons.liquor, keywords: 'liquor bebida alcoolica wine vinho'),
  CategoryIconOption(icon: Icons.emoji_food_beverage, keywords: 'tea cha drink bebida'),
  CategoryIconOption(icon: Icons.takeout_dining, keywords: 'takeout delivery entrega marmita'),
  CategoryIconOption(icon: Icons.set_meal, keywords: 'sushi japanese japonesa fish peixe'),

  // ── Groceries & shopping ─────────────────────────────────────────
  CategoryIconOption(icon: Icons.shopping_cart, keywords: 'cart carrinho shopping compras grocery mercado'),
  CategoryIconOption(icon: Icons.shopping_bag, keywords: 'shopping bag sacola compras'),
  CategoryIconOption(icon: Icons.shopping_basket, keywords: 'basket cesta grocery mercado compras'),
  CategoryIconOption(icon: Icons.local_grocery_store, keywords: 'grocery mercado supermarket supermercado'),
  CategoryIconOption(icon: Icons.local_mall, keywords: 'mall shopping center'),
  CategoryIconOption(icon: Icons.store, keywords: 'store loja shop'),
  CategoryIconOption(icon: Icons.storefront, keywords: 'shop loja store storefront'),
  CategoryIconOption(icon: Icons.local_offer, keywords: 'offer oferta promo desconto sale'),
  CategoryIconOption(icon: Icons.discount, keywords: 'discount desconto sale promo'),
  CategoryIconOption(icon: Icons.checkroom, keywords: 'clothes roupa fashion moda'),
  CategoryIconOption(icon: Icons.shopping_cart_checkout, keywords: 'checkout finalizar compra cart carrinho'),

  // ── Home & living ────────────────────────────────────────────────
  CategoryIconOption(icon: Icons.home, keywords: 'home casa house lar'),
  CategoryIconOption(icon: Icons.house, keywords: 'house casa home'),
  CategoryIconOption(icon: Icons.apartment, keywords: 'apartment apartamento building predio'),
  CategoryIconOption(icon: Icons.cottage, keywords: 'cottage casa de campo cabin'),
  CategoryIconOption(icon: Icons.bed, keywords: 'bed cama bedroom quarto'),
  CategoryIconOption(icon: Icons.weekend, keywords: 'sofa couch sala living room'),
  CategoryIconOption(icon: Icons.chair, keywords: 'chair cadeira furniture movel'),
  CategoryIconOption(icon: Icons.kitchen, keywords: 'kitchen cozinha fridge geladeira'),
  CategoryIconOption(icon: Icons.bathtub, keywords: 'bathtub banheira bathroom banheiro'),
  CategoryIconOption(icon: Icons.shower, keywords: 'shower chuveiro bathroom banheiro'),
  CategoryIconOption(icon: Icons.lightbulb, keywords: 'light luz lamp lampada idea'),
  CategoryIconOption(icon: Icons.bolt, keywords: 'energy energia electric eletricidade luz'),
  CategoryIconOption(icon: Icons.water_drop, keywords: 'water agua plumbing encanamento'),
  CategoryIconOption(icon: Icons.local_fire_department, keywords: 'gas fire fogo botijao'),
  CategoryIconOption(icon: Icons.cleaning_services, keywords: 'cleaning limpeza housekeeping faxina'),
  CategoryIconOption(icon: Icons.local_laundry_service, keywords: 'laundry lavanderia roupa'),
  CategoryIconOption(icon: Icons.dry_cleaning, keywords: 'dry cleaning lavanderia roupa'),
  CategoryIconOption(icon: Icons.iron, keywords: 'iron ferro passar roupa'),
  CategoryIconOption(icon: Icons.fireplace, keywords: 'fireplace lareira heating aquecimento'),
  CategoryIconOption(icon: Icons.foundation, keywords: 'house casa renovation reforma'),
  CategoryIconOption(icon: Icons.handyman, keywords: 'handyman repair conserto reparo tool ferramenta'),
  CategoryIconOption(icon: Icons.build, keywords: 'tools ferramentas repair conserto'),
  CategoryIconOption(icon: Icons.plumbing, keywords: 'plumbing encanamento pipe cano'),

  // ── Utilities & connectivity ─────────────────────────────────────
  CategoryIconOption(icon: Icons.wifi, keywords: 'wifi internet rede'),
  CategoryIconOption(icon: Icons.router, keywords: 'router roteador internet'),
  CategoryIconOption(icon: Icons.signal_cellular_alt, keywords: 'signal sinal data dados celular'),
  CategoryIconOption(icon: Icons.cell_tower, keywords: 'tower antena network rede'),
  CategoryIconOption(icon: Icons.phone, keywords: 'phone telefone call ligacao'),
  CategoryIconOption(icon: Icons.smartphone, keywords: 'smartphone celular phone telefone'),

  // ── Transportation ───────────────────────────────────────────────
  CategoryIconOption(icon: Icons.directions_car, keywords: 'car carro vehicle veiculo auto automovel transport transporte'),
  CategoryIconOption(icon: Icons.directions_bus, keywords: 'bus onibus transport transporte'),
  CategoryIconOption(icon: Icons.directions_subway, keywords: 'subway metro transport transporte'),
  CategoryIconOption(icon: Icons.directions_railway, keywords: 'train trem transport transporte'),
  CategoryIconOption(icon: Icons.directions_boat, keywords: 'boat barco ship navio'),
  CategoryIconOption(icon: Icons.directions_bike, keywords: 'bike bicicleta bicycle bici'),
  CategoryIconOption(icon: Icons.two_wheeler, keywords: 'motorcycle moto motocicleta'),
  CategoryIconOption(icon: Icons.electric_scooter, keywords: 'scooter patinete electric eletrico'),
  CategoryIconOption(icon: Icons.electric_car, keywords: 'electric car carro eletrico ev'),
  CategoryIconOption(icon: Icons.local_taxi, keywords: 'taxi cab uber 99 carro'),
  CategoryIconOption(icon: Icons.airport_shuttle, keywords: 'shuttle van transport transporte'),
  CategoryIconOption(icon: Icons.flight, keywords: 'flight voo plane aviao travel viagem'),
  CategoryIconOption(icon: Icons.flight_takeoff, keywords: 'flight voo takeoff decolagem travel'),
  CategoryIconOption(icon: Icons.local_gas_station, keywords: 'gas combustivel posto fuel gasolina'),
  CategoryIconOption(icon: Icons.ev_station, keywords: 'ev charging carregador eletrico station'),
  CategoryIconOption(icon: Icons.local_parking, keywords: 'parking estacionamento'),
  CategoryIconOption(icon: Icons.local_shipping, keywords: 'truck caminhao shipping entrega delivery'),
  CategoryIconOption(icon: Icons.commute, keywords: 'commute transport transporte trajeto'),
  CategoryIconOption(icon: Icons.traffic, keywords: 'traffic transito semaforo'),

  // ── Health & wellness ────────────────────────────────────────────
  CategoryIconOption(icon: Icons.local_hospital, keywords: 'hospital saude health'),
  CategoryIconOption(icon: Icons.medical_services, keywords: 'medical medico saude health'),
  CategoryIconOption(icon: Icons.medication, keywords: 'medication remedio pharmacy farmacia'),
  CategoryIconOption(icon: Icons.vaccines, keywords: 'vaccine vacina injection injecao'),
  CategoryIconOption(icon: Icons.healing, keywords: 'healing curativo bandage'),
  CategoryIconOption(icon: Icons.health_and_safety, keywords: 'health saude safety seguro plano'),
  CategoryIconOption(icon: Icons.monitor_heart, keywords: 'heart coracao health saude'),
  CategoryIconOption(icon: Icons.favorite, keywords: 'heart coracao love amor'),
  CategoryIconOption(icon: Icons.fitness_center, keywords: 'gym academia fitness exercicio'),
  CategoryIconOption(icon: Icons.self_improvement, keywords: 'yoga meditation meditacao wellbeing bemestar'),
  CategoryIconOption(icon: Icons.spa, keywords: 'spa wellness bemestar relax'),
  CategoryIconOption(icon: Icons.psychology, keywords: 'therapy terapia psychology psicologia'),
  CategoryIconOption(icon: Icons.bloodtype, keywords: 'blood sangue donation doacao'),

  // ── Education & work ─────────────────────────────────────────────
  CategoryIconOption(icon: Icons.school, keywords: 'school escola education educacao study estudo'),
  CategoryIconOption(icon: Icons.menu_book, keywords: 'book livro reading leitura'),
  CategoryIconOption(icon: Icons.auto_stories, keywords: 'story livro book reading'),
  CategoryIconOption(icon: Icons.science, keywords: 'science ciencia chemistry quimica lab'),
  CategoryIconOption(icon: Icons.calculate, keywords: 'calculator calculadora math matematica'),
  CategoryIconOption(icon: Icons.draw, keywords: 'draw desenho pen caneta'),
  CategoryIconOption(icon: Icons.palette, keywords: 'art arte palette paleta paint pintura'),
  CategoryIconOption(icon: Icons.brush, keywords: 'brush pincel paint pintura art arte'),
  CategoryIconOption(icon: Icons.work, keywords: 'work trabalho job emprego briefcase pasta'),
  CategoryIconOption(icon: Icons.business_center, keywords: 'business negocio briefcase pasta work trabalho'),
  CategoryIconOption(icon: Icons.business, keywords: 'business empresa company office escritorio'),
  CategoryIconOption(icon: Icons.badge, keywords: 'badge cracha id identidade'),
  CategoryIconOption(icon: Icons.computer, keywords: 'computer computador work trabalho'),
  CategoryIconOption(icon: Icons.laptop, keywords: 'laptop notebook computer computador'),

  // ── Entertainment & subscriptions ────────────────────────────────
  CategoryIconOption(icon: Icons.movie, keywords: 'movie filme cinema'),
  CategoryIconOption(icon: Icons.theaters, keywords: 'theater cinema teatro'),
  CategoryIconOption(icon: Icons.live_tv, keywords: 'tv television televisao stream'),
  CategoryIconOption(icon: Icons.music_note, keywords: 'music musica song musica'),
  CategoryIconOption(icon: Icons.library_music, keywords: 'music musica library biblioteca'),
  CategoryIconOption(icon: Icons.podcasts, keywords: 'podcast audio'),
  CategoryIconOption(icon: Icons.headphones, keywords: 'headphones fone audio music musica'),
  CategoryIconOption(icon: Icons.sports_esports, keywords: 'game jogo videogame esports'),
  CategoryIconOption(icon: Icons.videogame_asset, keywords: 'videogame jogo controle controller'),
  CategoryIconOption(icon: Icons.casino, keywords: 'casino gambling aposta'),
  CategoryIconOption(icon: Icons.celebration, keywords: 'celebration festa party comemoracao'),
  CategoryIconOption(icon: Icons.festival, keywords: 'festival evento event'),
  CategoryIconOption(icon: Icons.subscriptions, keywords: 'subscription assinatura streaming'),
  CategoryIconOption(icon: Icons.cloud, keywords: 'cloud nuvem storage armazenamento'),

  // ── Sports ────────────────────────────────────────────────────────
  CategoryIconOption(icon: Icons.sports_soccer, keywords: 'soccer football futebol'),
  CategoryIconOption(icon: Icons.sports_basketball, keywords: 'basketball basquete'),
  CategoryIconOption(icon: Icons.sports_volleyball, keywords: 'volleyball volei'),
  CategoryIconOption(icon: Icons.sports_tennis, keywords: 'tennis tenis'),
  CategoryIconOption(icon: Icons.sports_baseball, keywords: 'baseball beisebol'),
  CategoryIconOption(icon: Icons.sports_football, keywords: 'football americano nfl'),
  CategoryIconOption(icon: Icons.sports_golf, keywords: 'golf golfe'),
  CategoryIconOption(icon: Icons.surfing, keywords: 'surf surfar'),
  CategoryIconOption(icon: Icons.hiking, keywords: 'hiking caminhada trilha'),
  CategoryIconOption(icon: Icons.pool, keywords: 'pool piscina swimming natacao'),

  // ── Travel & places ──────────────────────────────────────────────
  CategoryIconOption(icon: Icons.beach_access, keywords: 'beach praia travel viagem'),
  CategoryIconOption(icon: Icons.hotel, keywords: 'hotel pousada hospedagem stay'),
  CategoryIconOption(icon: Icons.luggage, keywords: 'luggage mala bag bagagem travel viagem'),
  CategoryIconOption(icon: Icons.card_travel, keywords: 'travel viagem business trip'),
  CategoryIconOption(icon: Icons.map, keywords: 'map mapa location lugar'),
  CategoryIconOption(icon: Icons.place, keywords: 'place lugar location localizacao pin'),
  CategoryIconOption(icon: Icons.explore, keywords: 'explore explorar travel viagem compass bussola'),
  CategoryIconOption(icon: Icons.terrain, keywords: 'mountain montanha terrain terreno'),
  CategoryIconOption(icon: Icons.attractions, keywords: 'attractions atracoes park parque'),
  CategoryIconOption(icon: Icons.public, keywords: 'world mundo travel viagem global'),

  // ── People, family, gifts ────────────────────────────────────────
  CategoryIconOption(icon: Icons.person, keywords: 'person pessoa user usuario'),
  CategoryIconOption(icon: Icons.people, keywords: 'people pessoas group grupo'),
  CategoryIconOption(icon: Icons.family_restroom, keywords: 'family familia'),
  CategoryIconOption(icon: Icons.child_care, keywords: 'baby bebe child crianca infant'),
  CategoryIconOption(icon: Icons.child_friendly, keywords: 'stroller carrinho baby bebe'),
  CategoryIconOption(icon: Icons.escalator_warning, keywords: 'parent pais father mother pai mae'),
  CategoryIconOption(icon: Icons.elderly, keywords: 'elderly idoso senior'),
  CategoryIconOption(icon: Icons.pets, keywords: 'pet animal dog cachorro cat gato'),
  CategoryIconOption(icon: Icons.card_giftcard, keywords: 'gift presente'),
  CategoryIconOption(icon: Icons.redeem, keywords: 'gift presente redeem voucher'),
  CategoryIconOption(icon: Icons.volunteer_activism, keywords: 'donation doacao charity caridade'),

  // ── Personal care & beauty ───────────────────────────────────────
  CategoryIconOption(icon: Icons.content_cut, keywords: 'haircut cabelo barbeiro salon salao'),
  CategoryIconOption(icon: Icons.face, keywords: 'face rosto beauty beleza'),
  CategoryIconOption(icon: Icons.face_retouching_natural, keywords: 'beauty beleza skincare'),

  // ── Misc / catch-alls ────────────────────────────────────────────
  CategoryIconOption(icon: Icons.gavel, keywords: 'law legal advogado justica'),
  CategoryIconOption(icon: Icons.security, keywords: 'security seguranca insurance seguro'),
  CategoryIconOption(icon: Icons.assignment, keywords: 'task tarefa document documento'),
  CategoryIconOption(icon: Icons.event, keywords: 'event evento calendar calendario'),
  CategoryIconOption(icon: Icons.event_available, keywords: 'appointment agendamento booking reserva'),
  CategoryIconOption(icon: Icons.notifications, keywords: 'notification notificacao alert alerta'),
  CategoryIconOption(icon: Icons.star, keywords: 'star estrela favorite favorito'),
  CategoryIconOption(icon: Icons.bookmark, keywords: 'bookmark marcador save salvar'),
  CategoryIconOption(icon: Icons.label, keywords: 'label etiqueta tag'),
  CategoryIconOption(icon: Icons.flag, keywords: 'flag bandeira goal meta'),
  CategoryIconOption(icon: Icons.local_florist, keywords: 'flower flor garden jardim'),
  CategoryIconOption(icon: Icons.agriculture, keywords: 'agriculture agricultura farm fazenda tractor trator'),
  CategoryIconOption(icon: Icons.eco, keywords: 'eco green verde plant planta sustainability sustentavel'),
];
